"""
export_static.py
----------------
Stage 5b: build a static snapshot of the dashboard for hosting with no server.

GitHub Pages can serve HTML/JS but not Python, so this script asks a RUNNING
Aquapurity API for every request the dashboard can ever make and writes the
answers to docs/data/*.json. docs/index.html then reads those files instead of
calling the API (see the static-mode branch of apiFetch in app/index.html).

This is a faithful copy, not a re-implementation: the responses come from the
real HTTP endpoints, so the static build shows exactly what the API returns.
The interface space is small and fully deterministic (seed 42, CPU-only, no
user input beyond the controls), which is what makes precomputation possible:

    /wells    x 2 districts
    /sites    x 2 districts
    /rank     x 2 districts x 4 structures x 2 constrain modes   = 16
    /forecast x 120 wells x 3 horizons                          = 360
    /explain  x 120 wells x 3 horizons + 80 sites                = 440

Usage (with the API already running):

    uvicorn src.api:app --port 8000 &
    python src/export_static.py --api http://127.0.0.1:8000

Then serve docs/ (e.g. `python -m http.server 8095 -d docs`) or let GitHub
Pages publish the docs/ folder from the main branch.
"""

import argparse
import json
import os
import shutil
import sys

# keep the Windows console happy if anything non-ASCII is printed
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import urllib.error
import urllib.request

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
APP_DIR = os.path.join(ROOT, "app")
DOCS_DIR = os.path.join(ROOT, "docs")
DATA_OUT = os.path.join(DOCS_DIR, "data")

DISTRICTS = ["Thanjavur", "Pudukkottai"]
STRUCTURES = ["All", "Percolation Pond", "Check Dam", "Recharge Shaft"]
HORIZONS = [1, 3, 6]

BANNER = """<script>
/* Static snapshot build (GitHub Pages): there is no Python runtime here, so
   apiFetch() reads the precomputed JSON in ./data/ instead of a live API.
   Generated by src/export_static.py from a running uvicorn server - the
   responses below are the API's real output, not a re-implementation. */
window.AQUAPURITY_STATIC = true;
window.AQUAPURITY_API = '';
</script>
"""


def api(base, method, path, payload=None):
    """Call the API and return the decoded JSON body."""
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        base + path, data=data,
        headers={"Content-Type": "application/json"},
        method=method,
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as exc:
        raise SystemExit(f"!! {method} {path} -> HTTP {exc.code}: {exc.read()[:200]!r}")


def write_json(name, obj):
    path = os.path.join(DATA_OUT, name)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(obj, fh, separators=(",", ":"), sort_keys=True)
    size = os.path.getsize(path)
    print(f"  data/{name:22s} {size/1024:8.1f} KB")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--api", default="http://127.0.0.1:8000",
                    help="base URL of the running Aquapurity API")
    args = ap.parse_args()
    base = args.api.rstrip("/")

    # fail fast with a clear message if the API is not up
    health = api(base, "GET", "/health")
    print(f"[export] API at {base} is up ({health['status']}); building snapshot")

    # Write in place instead of wiping docs/ first: a web server or a file
    # sync client can hold a handle on the folder and make rmtree fail
    # half-way through, which would leave the published site broken.
    os.makedirs(DATA_OUT, exist_ok=True)

    # ── /wells and /sites, per district ──────────────────────────────────────
    print("[export] GET /wells, /sites")
    wells, sites = {}, {}
    for d in DISTRICTS:
        wells[d] = api(base, "GET", f"/wells?district={d}")
        sites[d] = api(base, "GET", f"/sites?district={d}")

    well_ids = [w["well_id"] for d in DISTRICTS for w in wells[d]["data"]]
    site_ids = [s["site_id"] for d in DISTRICTS for s in sites[d]["data"]]
    print(f"[export]   {len(well_ids)} wells, {len(site_ids)} sites")

    # ── /rank, every control combination ─────────────────────────────────────
    print("[export] POST /rank")
    rank = {}
    for d in DISTRICTS:
        for st in STRUCTURES:
            for exclude in (True, False):
                resp = api(base, "POST", "/rank", {
                    "district": d, "structure": st,
                    "exclude_constrained": exclude,
                })
                # lower-case the flag so the key matches the JavaScript
                # side, where String(true) is "true"
                rank[f"{d}|{st}|{str(exclude).lower()}"] = resp
    print(f"[export]   {len(rank)} rank responses")

    # ── /forecast and /explain, every well x horizon ─────────────────────────
    print("[export] POST /forecast, /explain (wells) - this runs the model, "
          "so it takes a minute")
    forecast, explain_wells = {}, {}
    for i, wid in enumerate(well_ids, 1):
        forecast[wid] = {}
        explain_wells[wid] = {}
        for h in HORIZONS:
            forecast[wid][str(h)] = api(base, "POST", "/forecast",
                                        {"well_id": wid, "horizon": h})
            explain_wells[wid][str(h)] = api(base, "POST", "/explain",
                                             {"well_id": wid, "horizon": h})
        if i % 20 == 0:
            print(f"[export]   {i}/{len(well_ids)} wells")

    # ── /explain, every site ────────────────────────────────────────────────
    print("[export] POST /explain (sites)")
    explain_sites = {}
    for sid in site_ids:
        explain_sites[sid] = api(base, "POST", "/explain", {"site_id": sid})
    print(f"[export]   {len(explain_sites)} site explanations")

    # ── write the JSON the dashboard reads ──────────────────────────────────
    print("[export] writing docs/data")
    write_json("wells.json", wells)
    write_json("sites.json", sites)
    write_json("rank.json", rank)
    write_json("forecast.json", forecast)
    write_json("explain_wells.json", explain_wells)
    write_json("explain_sites.json", explain_sites)

    # ── page + vendored libraries ───────────────────────────────────────────
    print("[export] writing docs/index.html and docs/vendor")
    with open(os.path.join(APP_DIR, "index.html"), "r", encoding="utf-8") as fh:
        html = fh.read()

    marker = "<script>\n" + "/" * 2 + " "
    # inject the static flag into the first script block (the app script)
    anchor = "<script>\n/* ─"
    if anchor not in html:
        raise SystemExit("!! could not find the app <script> block to patch")
    html = html.replace(anchor, BANNER + anchor, 1)
    with open(os.path.join(DOCS_DIR, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(html)

    shutil.copytree(os.path.join(APP_DIR, "vendor"),
                    os.path.join(DOCS_DIR, "vendor"), dirs_exist_ok=True)
    # stop GitHub Pages from running Jekyll over the folder
    open(os.path.join(DOCS_DIR, ".nojekyll"), "w").close()

    print(f"[export] done -> {DOCS_DIR}")


if __name__ == "__main__":
    main()
